export enum Error {
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_FOUND = "USER_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  SESSION_FOUND = "SESSION_COOKIE_FOUND",
  SESSION_NOT_FOUND = "SESSION_COOKIE_NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
